### ISSUE TITLE
Explaining what the credit section does? Redundant, no?

### ISSUE THREAD

**Issue by gorbiz** [Zebra003/actionable-agile-tools#6]
See: https://github.com/Zebra003/actionable-agile-tools/blob/master/manuscript/00.Introduction.md#credit

Suggestion: thank "everyone" instead.

**Comment by Zebra003** [comment]
I am not sure I follow this report... What do you think should be changed?

**Comment by Zebra003** [comment]
Are you saying, don't explain the credit section, that it is entirely evident?

**Comment by gorbiz** [comment]
Yes, though I now see it having purpose: ~this isn't all me, credit will be attributed chapterly?
I'd either:
1. Remove it completely. Motivation: people will understand the credit boxes once they reach the first one, though it is nicer, more humble & customary to keep it.
2. Leave it as it is but clarify the last part (which now appears to refer to itself) "The credit section is to provide appreciation to others who were involved.", perhaps just saying "The credit boxes (at the end of each chapter)".

I'd vote for 2. :).

**Comment by Zebra003** [comment]
Done
